apiVersion: v1
kind: Pod
metadata:
  name: busybox-temp
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "while true; do wget -O- http://foo; sleep 1; done"