apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-logs-reader-binding
  namespace: default
subjects:
- kind: User
  name: example-user  # Replace with the username you want to grant access to
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-logs-reader
  apiGroup: rbac.authorization.k8s.io