apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"] #"pods" is for accessing pods, and "pods/log" is for accessing pod logs.
  verbs: ["get", "list", "watch"]
 
 
 
