apiVersion: v1
kind: Pod
metadata:
  name: nginx03
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30  # Delay to allow nginx to warm up
      periodSeconds: 10         # Checking every 10 seconds
      timeoutSeconds: 5         # Timeout for each probe
  restartPolicy: Always
 