apiVersion: v1
kind: Pod
metadata:
  name: box0
spec:
  containers:
  - name: main-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 30; touch /tmp/debug; sleep 30; rm /tmp/debug"]
  initContainers:
  - name: init-container
    image: busybox
    command: ["/bin/sh", "-c", "until [ -f /tmp/debug ]; do sleep 1; done"]
  restartPolicy: Always