apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2  # Number of retries before considering a job as failed
      activeDeadlineSeconds: 17  # Terminate the job if it takes more than 17 secs 
      template:
        spec:
          containers:
          - name: busybox-container
            image: busybox
            command:
            - /bin/sh
            - -c
            - date; echo "Hello from the Kubernetes cluster"
          restartPolicy: OnFailure