apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
  - name: container1
    image: busybox
    command: ["sh", "-c", "echo we are running; sleep 3600"]
  - name: container2
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
  - name: container3
    image: busybox
    command: ["sh", "-c", "sleep 3600"]