apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice
spec:
  template:
    spec:
      containers:
      - name: throw-dice
        image: kodekloud/throw-dice
      restartPolicy: Never
  backoffLimit: 10