apiVersion: v1
kind: Pod
metadata:
  name: ubuntu03
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add:
          - SYS_TIME
  - name: test-container
    image: ubuntu
    command: ["/bin/bash", "-c", "date -s '01JAN2020 10:00:00' && sleep 3600"]
    securityContext:
      capabilities:
        add:
          - SYS_TIME